### ISSUE TITLE
Error loading dynamically imported module: .../ui/assets/ProtectedRoute-97594811.js on Firefox

### ISSUE THREAD

**Issue by mz2** [canonical/lxd-ui#737] opened 2024-04-11 19:57 UTC
I get the following error message on Firefox 124.0.2 on Mantic, after having set up a fresh microcloud, and after having done the certificate dance. Issue only visible on Firefox (and it is fully reproducible), Chromium does not show it.

![image](https://github.com/canonical/lxd-ui/assets/71363/1518fb48-d42c-4b89-a1a5-b277217ab90d)

![image](https://github.com/canonical/lxd-ui/assets/71363/d4a14f61-26c3-42ac-aa7d-b28d3a383515)

**Comment by edlerd** [comment] 2024-04-11 20:50
Thank you for reaching out.

What version of LXD are you using?

I tested 5.21/stable and latest/stable and couldn't reproduce it in Firefox 124.0.2 yet.

**Comment by mz2** [comment] 2024-04-12 05:45
Also `5.21/stable` channel here (`lxd --version` reports `5.21.1 LTS`).

... and this is mad, when I tried again this morning, refreshing the browser tab, it loaded the page happily, i.e. fully reproducible last night, not reproducible any longer :exploding_head: 

Only thing I did differently this time morning was to turn off the duckduckgo ad blocker for the site (I then turned it back on after that successful load and it continues to happily render pages now).

**Comment by edlerd** [comment] 2024-04-12 06:04
Thanks for confirming it is not a code bug.

The reason for the bug yesterday might be, that microcloud is changing network configuration after setting it up. I think this happens in the background, probably while you were setting up the certificates. If this process is happening on the same host as the browser, the browser will cancel all open request at the moment the network changes. From the messages in your screenshots above, I suspect this might be the reason: Browser cancelled the request and the UI fails. I'll follow up with the LXD team to see if we can figure this out and change it. Or we might be able to change the UI so it retries on asset loading failures.

**Comment by edlerd** [comment] 2024-10-17 16:50
We recently merged a way to [retry for this exact error](https://github.com/canonical/lxd-ui/pull/927). So if the network is unstable, the UI will try to reload instead of crashing right away.

**Closed by edlerd** 2024-10-17 16:50 UTC
