### ISSUE TITLE
Unable to set up multiple lxd web ui instances on localhost

### ISSUE THREAD

**Issue by serge-vk** [canonical/lxd-ui#966] opened 2024-10-22 21:50 UTC
Maybe, I am not doing things right, but I need to manage two different LXD systems whose web interfaces are ssh-tunnelled to different ports on localhost. I am able to set up one of them, but when I try adding another, I always get the `Error using token.
No matching certificate add operation found`. This happens either with an existing certificate or with a new one. I wonder if this is possible because I do not see an easy way to use different addresses for LXD systems, which are behind firewalls.

**Comment by edlerd** [comment] 2024-10-22 22:13
I haven't seen the error you described, but here are some options that might use to unblock:

1. Use different DNS names for localhost, you can set them up in /etc/hosts
2. Use https://127.0.0.1:123 for one and Https://localhost:234 for the other or Https://0.0.0.0:345 for a third one. Here 123, 234 and 345 are the little cal ports.

**Comment by serge-vk** [comment] 2024-10-23 00:00
If I have a working LXD interface at `127.0.0.1:123`, FireFox does not allow `localhost:234` or `[::1]:234` to use for another. 
I've managed to make it work by adding another local interface at `127.0.0.2`, but it seems strange that having different ports is not enough and I must use a different address to have such a simple thing. 
It looks like if I have to manage a third LXD system, I will need to add yet another local address. Maybe, this is a FireFox limitation, though? I am not sure I will have the time to test this on a different browser.

**Comment by edlerd** [comment] 2024-10-23 11:33
I think going with dns names would be a more sustainable approach, as you can create an infinite amount, unlike with local addresses.

Closing this for now, as the issue is not a bug or feature request for lxd-ui. Please use the [lxd discourse forum](https://discourse.ubuntu.com/c/lxd/126) for questions regarding deployment.

**Closed by edlerd** 2024-10-23 11:33 UTC

**Comment by serge-vk** [comment] 2024-10-27 00:06
Although the issue is closed, I wanted to add one last bit for anyone who will run into this problem. Although I would have preferred not worrying about using a different address for each LXD system, it seems easy enough to work around because the localhost subnet is `127.0.0.1/8`. Therefore, in your ssh tunnel you are free to use any address of that subnet without explicitly creating it, and, if necessary, to specify a domain name in your `hosts` file.
