### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by markmorado** [canonical/lxd-ui#807] opened 2024-06-29 04:54 UTC
```
eG@https://10.10.11.254:8443/ui/assets/index-b3f3eaed.js:87:30823
ie@https://10.10.11.254:8443/ui/assets/FormMenuItem-f4d64986.js:1:5989
te@https://10.10.11.254:8443/ui/assets/FormMenuItem-f4d64986.js:1:4865
be@https://10.10.11.254:8443/ui/assets/FormMenuItem-f4d64986.js:1:7867
J@https://10.10.11.254:8443/ui/assets/NetworkForm-34d3abf4.js:1:4879
Zg@https://10.10.11.254:8443/ui/assets/index-b3f3eaed.js:38:19529
B1@https://10.10.11.254:8443/ui/assets/index-b3f3eaed.js:40:44027
L1@https://10.10.11.254:8443/ui/assets/index-b3f3eaed.js:40:39765
m$@https://10.10.11.254:8443/ui/assets/index-b3f3eaed.js:40:39693
Cd@https://10.10.11.254:8443/ui/assets/index-b3f3eaed.js:40:39545
Ym@https://10.10.11.254:8443/ui/assets/index-b3f3eaed.js:40:35913
F0@https://10.10.11.254:8443/ui/assets/index-b3f3eaed.js:40:36716
hi@https://10.10.11.254:8443/ui/assets/index-b3f3eaed.js:38:3274
Dn/<@https://10.10.11.254:8443/ui/assets/index-b3f3eaed.js:40:34246

```

**Comment by edlerd** [comment] 2024-06-29 21:21
Thanks for the report. This is a duplicate of  #787

**Closed by edlerd** 2024-06-29 21:21 UTC
