### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by fahrettinrizaergin** [canonical/lxd-ui#804] opened 2024-06-23 21:36 UTC
```
Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zg (https://88.88.1.71:8443/ui/assets/index-b3f3eaed.js:38:19733)
    at Am (https://88.88.1.71:8443/ui/assets/index-b3f3eaed.js:40:3139)
    at B1 (https://88.88.1.71:8443/ui/assets/index-b3f3eaed.js:40:44801)
    at L1 (https://88.88.1.71:8443/ui/assets/index-b3f3eaed.js:40:39763)
    at m$ (https://88.88.1.71:8443/ui/assets/index-b3f3eaed.js:40:39691)
    at Cd (https://88.88.1.71:8443/ui/assets/index-b3f3eaed.js:40:39545)
    at Ym (https://88.88.1.71:8443/ui/assets/index-b3f3eaed.js:40:35913)
    at F0 (https://88.88.1.71:8443/ui/assets/index-b3f3eaed.js:40:36716)
    at hi (https://88.88.1.71:8443/ui/assets/index-b3f3eaed.js:38:3274)
    at eo (https://88.88.1.71:8443/ui/assets/index-b3f3eaed.js:40:37163)
```

**Comment by edlerd** [comment] 2024-06-25 21:51
Thank you for the report.

Can you provide additional info, like which page in the lxd-ui were you trying to access when this occurred or what operation was started?

**Comment by edlerd** [comment] 2024-07-07 19:35
Closing as a duplicate of #810

**Closed by edlerd** 2024-07-07 19:35 UTC
Labels: Bug 🐛, duplicate
