### ISSUE TITLE
LXD UI should display "total" utilization of Ceph pool based on the projected volum size rather than current use

### ISSUE THREAD

**Issue by grebennikov** [canonical/lxd-ui#751] opened 2024-04-25 03:05 UTC
Ceph allows thin provisioning of the volumes, and volume info displays "Usage" and "Total" size of the volume:

$ lxc storage volume info ceph1 t1
Name: t1
Type: custom
Content type: block
Usage: 0B
Total: 4.00GiB

In the UI the pool info is based on "Usage" of volumes, which is misleading and easily allows overprovisioning.

**Comment by edlerd** [comment] 2024-04-26 14:11
Thank you for reaching out!

@grebennikov what is your concern?

I checked the UI and CLI behaviour and everything seems to be in sync. Then again, I might have missed what exactly you were aiming for.

# thin storage volume

The UI is displaying the current usage for a thin provisioned ceph volume:

![image](https://github.com/canonical/lxd-ui/assets/1155472/03792898-b8dc-4563-ab85-b47280ba911c)

This is very similar to what the cli reports:

![image](https://github.com/canonical/lxd-ui/assets/1155472/bcfcc390-9b66-437f-b462-1f014425bb39)

# thin instance volume

For instance the UI reports usage as such:

![image](https://github.com/canonical/lxd-ui/assets/1155472/f1906def-87d1-40ba-8141-0eeaab397b3a)

which is the same as in the cli:

![image](https://github.com/canonical/lxd-ui/assets/1155472/2624ebe6-c2b5-4fe0-ae36-70c8491511c3)

# storage pool

As for the storage pool is reported in terms of actual usage:

![image](https://github.com/canonical/lxd-ui/assets/1155472/161e5991-16d9-425b-839a-ea193676f112)

which is the same as in the cli:

![image](https://github.com/canonical/lxd-ui/assets/1155472/8466db08-b3ec-412a-81be-fae1fbf383d3)

**Comment by tomponline** [comment] 2024-04-26 15:06
> Clarified offline: This is about the insight on a storage pool to see quickly the total amount of allocated space in that pool. Even though only some amount of that allocated space is reported as used due to thin provisioning.
> 
> See also [canonical/lxd#13384](https://github.com/canonical/lxd/issues/13384) for the backend story.

Is there anything to fix in the UI though? We shouldn't be showing different metrics with labels that differ from that of the LXD `lxc` CLI. 

If the root cause of the issue is https://github.com/canonical/lxd/issues/13384 we should just focus on that.

**Comment by edlerd** [comment] 2024-04-26 15:08
I agree, then let's close this one.

**Closed by edlerd** 2024-04-26 15:08 UTC
