### ISSUE TITLE
page no longer load after creating first Instance

### ISSUE THREAD

**Issue by aryanrajseo** [canonical/lxd-ui#1027] opened 2024-12-12 10:18 UTC
Hi i setup the lxd again, with crt file and everything working but after creating the first container 24.04 LTS, it no longer loads.

This is second try and is same issue.

Thanks.

<img width="1361" alt="SCR-20241212-nxdm-2" src="https://github.com/user-attachments/assets/60e6c1ed-670c-44d2-8878-ee7a60768326" />

**Comment by aryanrajseo** [comment] 2024-12-12 10:53
also forced to enter user password 4-5times

<img width="1026" alt="image" src="https://github.com/user-attachments/assets/bdd256a3-86c5-4f71-844f-b7e151d22e5b" />

**Comment by mas-who** [comment] 2024-12-12 15:20
Hi @aryanrajseo thanks for reporting. Looking at the network requests, seems like you are getting 500 responses indicating your LXD server may be down, would you be able to check and confirm that?

**Comment by aryanrajseo** [comment] 2024-12-13 02:10
hi @mas-who, the server is up, the ip:8443 is up, the setting page is also visible. i can send the details in private if devs want to debug.

**Comment by aryanrajseo** [comment] 2024-12-13 03:18
given a retry on new dedicated server and having similar issues with ssh login no longer works. i think i am doing something wrong. i am not using root user but ubuntu@ip. with sudo su access for root install.

i am uploading .crt file with ubuntu user via sftp and then adding with sudo. the uploading part of .crt file is difficult for me.

if devs want to recheck, i can give a fresh reinstall of the server so they can review it. would be great if they screencast the process.

**Comment by mas-who** [comment] 2024-12-13 08:38
> given a retry on new dedicated server and having similar issues with ssh login no longer works. i think i am doing something wrong. i am not using root user but ubuntu@ip. with sudo su access for root install.
> 
> i am uploading .crt file with ubuntu user via sftp and then adding with sudo. the uploading part of .crt file is difficult for me.
> 
> if devs want to recheck, i can give a fresh reinstall of the server so they can review it. would be great if they screencast the process.

Yes I believe this is not a bug in the UI as you have suggested, instead it sounds like the server setup may need to be adjusted. A few things to confirm first, where are you hosting your server? Also how are you uploading the .crt file via sftp without ssh access?

**Comment by aryanrajseo** [comment] 2024-12-13 08:46
@mas-who i am using OVH. default user is ubuntu with ssd access. i uploaded crt using sftp and then added it using ssh command. however, i recently retried with ssh root and scp and it is the same issue. here is the complete process i followed https://discourse.ubuntu.com/t/page-no-longer-load-after-creating-first-instance/51126

here IP is server ip.
```
sudo scp Downloads/lxd-ui-IP.crt root@IP:/root/
sudo lxc config trust add lxd-ui-IP.crt
```

**Comment by mas-who** [comment] 2024-12-13 12:56
I actually can't see any issue with your lxd setup. When you run lxc commands on your remote host currently, do you get any errors? Also is your host address a reserved static IP? The 404 error you are seeing in the UI is because it cannot reach the lxd server. Based on the information provided, it sounds like something went wrong when you created the first instance and may have caused the lxd server or event the host to go down. @edlerd any thoughts?

**Comment by aryanrajseo** [comment] 2024-12-13 13:04
> I actually can't see any issue with your lxd setup. When you run lxc commands on your remote host currently, do you get any errors? Also is your host address a reserved static IP? The 404 error you are seeing in the UI is because it cannot reach the lxd server. Based on the information provided, it sounds like something went wrong when you created the first instance and may have caused the lxd server or event the host to go down. @edlerd any thoughts?

It has a static ip. after i completed the install, i created the Instance using the UI only. there was no error.  i have a screencast which i can share in private due to ip. i can also share a fresh server detail that you can try. i would appreciate your help with this.

**Comment by edlerd** [comment] 2024-12-15 12:36
Thank you for the report.

This sounds like an issue with the deployment, maybe the external IP or domain you are using is not setup correctly. The 5xx error points to a backend problem. Additional logfiles, like running `dmesg` or `grep lxd /var/log/syslog` could give a hint of what is going wrong.

I'm closing this here, as it is not a bug with the UI code itself, and this is the repo for it. The lxd discussion forums are meant for those topics. Please continue the discussion [over there](https://discourse.ubuntu.com/t/page-no-longer-load-after-creating-first-instance/51126).

**Closed by edlerd** 2024-12-15 12:36 UTC

**Comment by aryanrajseo** [comment] 2024-12-15 12:53
@edlerd hi, the problem is the ssh stop working after this so there is no way to get any log file. hostname, static ip all seems correct as far i know. i would request if you give 5minutes and check it on newly created server to reconfirm. also i don't get any reply there on the forum post.
