### ISSUE TITLE
Terminal doesn't reliably display tabular data

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd-ui#550] opened 2023-11-23 13:12 UTC
When using the terminal, running a command that produces tabular data, e.g. `lxc list` often appears malformed. 
I've also seen this with `microcloud init` too.

![Screenshot 2023-11-23 at 13-10-50 10 21 203 5 LXD UI](https://github.com/canonical/lxd-ui/assets/280181/4208f849-14ce-44a9-9b44-51d35f7cfeb9)

**Comment by edlerd** [comment] 2023-11-23 14:28
I assume this is a duplicate of https://github.com/canonical/lxd-ui/issues/537, for which we just opened a PR with a fix in https://github.com/canonical/lxd-ui/pull/547

**Closed by edlerd** 2023-11-23 14:28 UTC
